### ISSUE TITLE
clr-boot-manager not removing old kernels and filling 1GB /boot

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/clr-boot-manager#8]
### Please confirm there isn't an open report for this issue

- [x] I have searched through bug reports

### Summary

I received an error during the last software removal because there was not enough space in /boot

### Steps to reproduce

1. Install both the current and LTS kernels
2. Update the system over time (I haven't seen this error in months to be fair). Wait for 3 kernels to have been published.

### Expected result

Old kernels are removed, there remains enough space to install new kernels

### Actual result

```
[✓] Syncing filesystems                                                success  
[✓] Updating dynamic library cache                                     success  
[✗] Updating clr-boot-manager                                           failed  
  
A copy of the command output follows:  
  
[FATAL] cbm (../src/bootman/kernel.c:L740): Failed to install extra initrds /usr/lib64/kernel/initrd-com.solus-project.current.6.12.17-314: No space left on device  
[FATAL] cbm (../src/bootman/update.c:L250): Failed to install default-current kernel: ///usr/lib/kernel/com.solus-project.current.6.12.17-314  
  
  
[✗] Updating clr-boot-manager                                           failed  
  
A copy of the command output follows:  
  
[FATAL] cbm (../src/bootman/kernel.c:L740): Failed to install extra initrds /usr/lib64/kernel/initrd-com.solus-project.current.6.12.17-314: No space left on device  
[FATAL] cbm (../src/bootman/update.c:L250): Failed to install default-current kernel: ///usr/lib/kernel/com.solus-project.current.6.12.17-314
```

### Environment

- [x] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.7
KDE Plasma Version: 6.3.2
KDE Frameworks Version: 6.11.0
Qt Version: 6.8.2
Kernel Version: 6.12.12-313.current (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor 1: Intel® UHD Graphics
Graphics Processor 2: NVIDIA GeForce RTX 3060 Laptop GPU

### Other comments

Space usage on `/boot`
```
❯ df -h | rg "File|boot"
Filesystem               Size  Used Avail Use% Mounted on
/dev/nvme0n1p1           999M  984M   15M  99% /boot
```
Installed kernels.

```
❯ ll /boot/EFI/com.solus-project
total 848M
drwxr-xr-x 3 root root 4.0K Mar  3 19:51 ./
drwxr-xr-x 7 root root 4.0K Feb 25 11:06 ../
drwxr-xr-x 2 root root 4.0K Sep 16 14:06 fw/
-rwxr-xr-x 1 root root 928K Jan 10 11:02 bootloaderx64.efi*
-rwxr-xr-x 1 root root  152 Jan 10 11:02 BOOTX64.CSV*
-rwxr-xr-x 1 root root  48M Mar  3 10:19 freestanding-com.solus-project.nvidia-firmware*
-rwxr-xr-x 1 root root  67K Apr 24  2024 fwupdx64.efi*
-rwxr-xr-x 1 root root  76K Jan 10 11:02 grubx64.efi*
-rwxr-xr-x 1 root root  78M Feb  8 08:34 initrd-com.solus-project.current.6.12.12-313*
-rwxr-xr-x 1 root root  52M Feb  8 08:34 initrd-com.solus-project.current.6.12.12-313.nvidia*
-rwxr-xr-x 1 root root  77M Mar  3 10:19 initrd-com.solus-project.current.6.12.17-314*
-rwxr-xr-x 1 root root  77M Dec 18 04:56 initrd-com.solus-project.current.6.12.5-311*
-rwxr-xr-x 1 root root  52M Dec 18 04:56 initrd-com.solus-project.current.6.12.5-311.nvidia*
-rwxr-xr-x 1 root root  78M Jan 10 15:55 initrd-com.solus-project.current.6.12.9-312*
-rwxr-xr-x 1 root root  52M Jan 10 15:55 initrd-com.solus-project.current.6.12.9-312.nvidia*
-rwxr-xr-x 1 root root  44M Oct 26  2023 initrd-com.solus-project.current.6.5.9-262.nvidia*
-rwxr-xr-x 1 root root  68M Oct 23 06:28 initrd-com.solus-project.lts.6.6.58-258*
-rwxr-xr-x 1 root root  69M Feb  8 08:34 initrd-com.solus-project.lts.6.6.75-264*
-rwxr-xr-x 1 root root  68M Mar  3 10:19 initrd-com.solus-project.lts.6.6.80-265*
-rwxr-xr-x 1 root root  13M Feb  8 08:34 kernel-com.solus-project.current.6.12.12-313*
-rwxr-xr-x 1 root root  14M Mar  3 10:19 kernel-com.solus-project.current.6.12.17-314*
-rwxr-xr-x 1 root root  13M Dec 18 04:56 kernel-com.solus-project.current.6.12.5-311*
-rwxr-xr-x 1 root root  13M Jan 10 15:55 kernel-com.solus-project.current.6.12.9-312*
-rwxr-xr-x 1 root root  12M Oct 23 06:28 kernel-com.solus-project.lts.6.6.58-258*
-rwxr-xr-x 1 root root  13M Feb  8 08:34 kernel-com.solus-project.lts.6.6.75-264*
-rwxr-xr-x 1 root root  13M Mar  3 10:19 kernel-com.solus-project.lts.6.6.80-265*
-rwxr-xr-x 1 root root 829K Jan 10 11:02 mmx64.efi*
```

There are 3 LTS kernels, 4 current kernels and their respective nvidia files. There should only be 2 of each. The oldest are from October, so there have been many successful boots since then. The oldest kernels should have been automatically removed.

(I notice the nvidia file for 6.5.9, not sure why that's still there. Deleted that manually since clr-boot-manager didn't know about it)

**Comment by silkeh** [comment]
Can you provide the output of the following commands? Run `sudo clr-boot-manager mount-boot` beforehand.

```
sudo clr-boot-manager list-kernels
ls -l /boot/loader/entries/
ls -l /boot/EFI/com.solus-project/
ls -l /usr/lib/kernel/
ls -l /var/lib/kernel/
df -h /boot
```

And finally:

```
sudo env CBM_DEBUG=1 clr-boot-manager update
```

> (I notice the nvidia file for 6.5.9, not sure why that's still there. Deleted that manually since clr-boot-manager didn't know about it)

Please let me know if you find more leftover `.nvidia` files, that might indicate a cleanup issue.

**Comment by Almat0s** [comment]
Hey everyone,

thanks for your great work!!

I have the same issue, managed to get around the problem with some manual cleaning of old kernels, but this is probably just a solution till next kernel update.
Please find attached my output, several .nvidia files found.
Glad if you have an idea how to solve the issue.

KR

```
 sudo clr-boot-manager  list-kernels
 
   com.solus-project.current.6.12.19-315
* com.solus-project.lts.6.6.83-266
```
```
-ls -l /boot/loader/entries/
insgesamt 8
-rwxr-xr-x 1 root root 475 27. Mär 15:42 Solus-current-6.12.19-315.conf
-rwxr-xr-x 1 root root 460 28. Mär 19:08 Solus-lts-6.6.83-266.conf266.conf

```
```
ls -l /boot/EFI/com.solus-project/
insgesamt 379836
-rwxr-xr-x 1 root root   949424 28. Mär 18:58 bootloaderx64.efi
-rwxr-xr-x 1 root root      152 28. Mär 18:58 BOOTX64.CSV
-rwxr-xr-x 1 root root 65713156 27. Mär 15:03 freestanding-com.solus-project.nvidia-firmware
-rwxr-xr-x 1 root root    77616 28. Mär 18:58 grubx64.efi
-rwxr-xr-x 1 root root 80295929 27. Mär 15:42 initrd-com.solus-project.current.6.12.19-315
-rwxr-xr-x 1 root root 72185345 27. Mär 15:42 initrd-com.solus-project.current.6.12.19-315.nvidia
-rwxr-xr-x 1 root root 70343837 27. Mär 15:03 initrd-com.solus-project.lts.6.6.83-266
-rwxr-xr-x 1 root root 72187885 28. Mär 19:08 initrd-com.solus-project.lts.6.6.83-266.nvidia
-rwxr-xr-x 1 root root 13647152 27. Mär 15:03 kernel-com.solus-project.current.6.12.19-315
-rwxr-xr-x 1 root root 12684592 27. Mär 15:03 kernel-com.solus-project.lts.6.6.83-266
-rwxr-xr-x 1 root root   848080 28. Mär 18:58 mmx64.efi

```
```
ls -l /usr/lib/kernel/
insgesamt 330712
-rw-r--r-- 1 root root       16 14. Mär 23:16 cmdline-6.12.19-315.current
-rw-r--r-- 1 root root       16 14. Mär 23:30 cmdline-6.6.83-266.lts
drwxr-xr-x 2 root root     4096 24. Mär 19:04 cmdline.d
-rwxr-xr-x 1 root root 13647152 14. Mär 23:17 com.solus-project.current.6.12.19-315
-rwxr-xr-x 1 root root 12684592 14. Mär 23:30 com.solus-project.lts.6.6.83-266
-rw-r--r-- 1 root root   261848 14. Mär 23:16 config-6.12.19-315.current
-rw-r--r-- 1 root root   255379 14. Mär 23:30 config-6.6.83-266.lts
lrwxrwxrwx 1 root root       44 27. Mär 15:47 current-initrd -> initrd-com.solus-project.current.6.12.19-315
lrwxrwxrwx 1 root root       37 27. Mär 15:47 current-vmlinux -> com.solus-project.current.6.12.19-315
lrwxrwxrwx 1 root root       37 27. Mär 15:47 default-current -> com.solus-project.current.6.12.19-315
lrwxrwxrwx 1 root root       32 24. Mär 20:44 default-lts -> com.solus-project.lts.6.6.83-266
-rw------- 1 root root 80295929 14. Mär 23:17 initrd-com.solus-project.current.6.12.19-315
-rw-r--r-- 1 root root 72185345 20. Mär 00:29 initrd-com.solus-project.current.6.12.19-315.nvidia
-rw------- 1 root root 70343837 14. Mär 23:30 initrd-com.solus-project.lts.6.6.83-266
-rw-r--r-- 1 root root 72187885 20. Mär 00:29 initrd-com.solus-project.lts.6.6.83-266.nvidia
drwxr-xr-x 2 root root     4096 24. Mär 19:04 initrd.d
lrwxrwxrwx 1 root root       39 24. Mär 20:44 lts-initrd -> initrd-com.solus-project.lts.6.6.83-266
lrwxrwxrwx 1 root root       32 24. Mär 20:44 lts-vmlinux -> com.solus-project.lts.6.6.83-266
-rw-r--r-- 1 root root  8969405 14. Mär 23:16 System.map-6.12.19-315.current
-rw-r--r-- 1 root root  7779578 14. Mär 23:30 System.map-6.6.83-266.lts
```
```
ls -l /var/lib/kernel/
insgesamt 8
-rw-r--r-- 1 root root 22 27. Mär 15:03 k_booted_6.12.9-312.current
-rw-r--r-- 1 root root 22 28. Mär 18:55 k_booted_6.6.83-266.lts
```
```
sudo env CBM_DEBUG=1 clr-boot-manager update
[sudo] password for keeper:
[DEBUG] cbm (../src/cli/cli.c:L142): No such file: //etc/kernel/update_efi_vars
[INFO] cbm (../src/bootman/bootman.c:L815): Current running kernel: 6.6.83-266.lts
[INFO] cbm (../src/bootman/sysconfig.c:L179): Discovered UEFI ESP: /dev/disk/by-partuuid/a086a2f5-6845-43d8-a93a-85a8df563965
[INFO] cbm (../src/bootman/sysconfig.c:L256): Fully resolved boot device: /dev/nvme1n1p1
[DEBUG] cbm (../src/lib/probe.c:L290): Root device exists on device-mapper configuration
[DEBUG] cbm (../src/bootman/bootman.c:L179): No console configuration in //etc/vconsole.conf
[DEBUG] cbm (../src/bootman/bootman.c:L145): shim-systemd caps: 0x26, wanted: 0x26
[DEBUG] cbm (../src/bootman/bootman.c:L160): UEFI boot now selected (shim-systemd)
[INFO] cbm (../src/bootman/bootman.c:L835): path ///etc/kernel/initrd.d does not exist
[DEBUG] cbm (../src/bootman/bootman.c:L856): Non regular file: ///usr/lib64/kernel/initrd.d/., skipping.
[DEBUG] cbm (../src/bootman/bootman.c:L856): Non regular file: ///usr/lib64/kernel/initrd.d/.., skipping.
[INFO] cbm (../src/bootman/bootman.c:L531): Checking for mounted boot dir
[INFO] cbm (../src/bootman/bootman.c:L538): boot_dir is already mounted: /boot
[DEBUG] cbm (../src/bootman/update.c:L164): Now beginning update_native
[DEBUG] cbm (../src/bootman/update.c:L173): update_native: 2 available kernels
[DEBUG] cbm (../src/bootman/update.c:L191): update_native: Running kernel is (lts) ///usr/lib/kernel/com.solus-project.lts.6.6.83-266
[SUCCESS] cbm (../src/bootman/update.c:L205): update_native: Bootloader updated
[DEBUG] cbm (../src/bootman/kernel.c:L650): installing extra initrd: /usr/lib64/kernel/initrd-com.solus-project.lts.6.6.83-266.nvidia
[DEBUG] cbm (../src/bootloaders/systemd-class.c:L220): adding extra initrd to bootloader: initrd-com.solus-project.lts.6.6.83-266.nvidia
[SUCCESS] cbm (../src/bootman/update.c:L220): update_native: Repaired running kernel ///usr/lib/kernel/com.solus-project.lts.6.6.83-266
[DEBUG] cbm (../src/bootman/update.c:L230): update_native: Checking kernels for type lts
[INFO] cbm (../src/bootman/update.c:L243): update_native: Default kernel for type lts is ///usr/lib/kernel/com.solus-project.lts.6.6.83-266
[DEBUG] cbm (../src/bootman/kernel.c:L650): installing extra initrd: /usr/lib64/kernel/initrd-com.solus-project.lts.6.6.83-266.nvidia
[DEBUG] cbm (../src/bootloaders/systemd-class.c:L220): adding extra initrd to bootloader: initrd-com.solus-project.lts.6.6.83-266.nvidia
[SUCCESS] cbm (../src/bootman/update.c:L255): update_native: Installed tip for lts: ///usr/lib/kernel/com.solus-project.lts.6.6.83-266
[DEBUG] cbm (../src/bootman/kernel.c:L650): installing extra initrd: /usr/lib64/kernel/initrd-com.solus-project.lts.6.6.83-266.nvidia
[DEBUG] cbm (../src/bootloaders/systemd-class.c:L220): adding extra initrd to bootloader: initrd-com.solus-project.lts.6.6.83-266.nvidia
[SUCCESS] cbm (../src/bootman/update.c:L269): update_native: Installed last_good kernel (lts) (///usr/lib/kernel/com.solus-project.lts.6.6.83-266)
[DEBUG] cbm (../src/bootman/update.c:L280): update_native: Analyzing for type lts: ///usr/lib/kernel/com.solus-project.lts.6.6.83-266
[DEBUG] cbm (../src/bootman/update.c:L285): update_native: Skipping running kernel
[DEBUG] cbm (../src/bootman/update.c:L230): update_native: Checking kernels for type current
[INFO] cbm (../src/bootman/update.c:L243): update_native: Default kernel for type current is ///usr/lib/kernel/com.solus-project.current.6.12.19-315
[DEBUG] cbm (../src/bootman/kernel.c:L650): installing extra initrd: /usr/lib64/kernel/initrd-com.solus-project.current.6.12.19-315.nvidia
[DEBUG] cbm (../src/bootloaders/systemd-class.c:L220): adding extra initrd to bootloader: initrd-com.solus-project.current.6.12.19-315.nvidia
[SUCCESS] cbm (../src/bootman/update.c:L255): update_native: Installed tip for current: ///usr/lib/kernel/com.solus-project.current.6.12.19-315
[DEBUG] cbm (../src/bootman/update.c:L273): update_native: No last_good kernel for type current
[DEBUG] cbm (../src/bootman/update.c:L280): update_native: Analyzing for type current: ///usr/lib/kernel/com.solus-project.current.6.12.19-315
[INFO] cbm (../src/bootman/update.c:L288): update_native: not-running: ///usr/lib/kernel/com.solus-project.current.6.12.19-315
[DEBUG] cbm (../src/bootman/update.c:L291): update_native: Skipping default-current: ///usr/lib/kernel/com.solus-project.current.6.12.19-315
[INFO] cbm (../src/bootman/bootman.c:L531): Checking for mounted boot dir
[INFO] cbm (../src/bootman/bootman.c:L538): boot_dir is already mounted: /boot
[SUCCESS] cbm (../src/bootman/update.c:L338): update_native: Default kernel for lts is ///usr/lib/kernel/com.solus-project.lts.6.6.83-266
[DEBUG] cbm (../src/bootman/update.c:L353): No kernel removals found

```

**Comment by silkeh** [comment]
@Almat0s: thanks for the report! I don't see anything strange from your output: one `lts` and one `current` kernel is the minimum when having both installed. The `.nvidia` files are also normal, as long as they accompany kernels and you have the nvidia drivers installed. Is this from after the manual clean up?

**Comment by zmaint** [comment]
I continue to run into this issue on 2 PC's.  Both are Solus Plasma, both have nvidia cards (3060 and 4070).   On 3/15 I manually removed all but the most current kernel and the most recent backup (it had 3 saved and obviously there was no room for the 4th).  Today 4/15, same issue.  Had 3 more kernels installed and it failed to find room for the 4th.   I only have physical access to one of the PC's (one is a state away on family member's).  Would be happy to run anything to help with trouble shooting.  

I updated mine last night (the 4070), no issues.  Oddly enough I had 2 kernels before the update and now I only have 1.  I thought it is supposed to keep 2?  Curious as to why sometimes it deletes none when it should and sometimes it deletes when it should not?

Before update
zsolus@zsolus ~ $ sudo clr-boot-manager list-kernels
com.solus-project.current.6.12.21-316
com.solus-project.current.6.12.19-315

After update
zsolus@zsolus ~ $ sudo clr-boot-manager list-kernels
com.solus-project.current.6.12.21-316

I have 2 all AMD laptops, 1 all AMD mini PC, 4 other all Intel PC, and 2 other Intel/Nvidia PC that are at friends and family.  They are all on Plasma and so far none of them have had any issues with this.   The two PC's that have had the issue to date are both AMD processors with Nvidia cards running Plasma.  No one is running the LTS kernel.  Hope this helps.

**Comment by silkeh** [comment]
@zmaint: please provide the output from the commands in [this comment](https://github.com/getsolus/clr-boot-manager/issues/8) when you run in to this issue to help us debug this further.

> Oddly enough I had 2 kernels before the update and now I only have 1. I thought it is supposed to keep 2? Curious as to why sometimes it deletes none when it should and sometimes it deletes when it should not?

`clr-boot-manager update` removes everything except for the latest, the running, and the last successfully updated kernel. This is usually two (currently running kernel and the new kernel), but only one if you reboot to the latest kernel.

> I have 2 all AMD laptops, 1 all AMD mini PC, 4 other all Intel PC, and 2 other Intel/Nvidia PC that are at friends and family. They are all on Plasma and so far none of them have had any issues with this. The two PC's that have had the issue to date are both AMD processors with Nvidia cards running Plasma. No one is running the LTS kernel. Hope this helps.

This having to do with Nvidia makes sense because they ship additional files. These aren't that small either. There might also be some cleanup bugs for these files, but I would need output from the commands in [this comment](https://github.com/getsolus/clr-boot-manager/issues/8) to be sure.

**Comment by zmaint** [comment]
Just tried to update, I was not able to update last week so this is a week behind.

```
 [✓] Syncing filesystems                                                success
 [✓] Updating dynamic library cache                                     success
 [✗] Updating clr-boot-manager                                           failed

A copy of the command output follows:

[FATAL] cbm (../src/bootman/kernel.c:L740): Failed to install extra initrds /usr/lib64/kernel/initrd-com.solus-project.current.6.14.6-319: No space left on device
[FATAL] cbm (../src/bootman/update.c:L250): Failed to install default-current kernel: ///usr/lib/kernel/com.solus-project.current.6.14.6-319


 [✗] Updating clr-boot-manager                                           failed

A copy of the command output follows:

[FATAL] cbm (../src/bootman/kernel.c:L740): Failed to install extra initrds /usr/lib64/kernel/initrd-com.solus-project.current.6.14.6-319: No space left on device
[FATAL] cbm (../src/bootman/update.c:L250): Failed to install default-current kernel: ///usr/lib/kernel/com.solus-project.current.6.14.6-319


zsolus@zsolus ~ $ sudo clr-boot-manager list-kernels
  com.solus-project.current.6.14.6-319
* com.solus-project.current.6.14.4-318
  com.solus-project.current.6.12.23-317

zsolus@zsolus ~ $ ls -l /boot/loader/entries/
total 8
-rwxr-xr-x 1 root root 479 Apr 25 09:58 Solus-current-6.12.23-317.conf
-rwxr-xr-x 1 root root 476 May  8 08:38 Solus-current-6.14.4-318.conf

zsolus@zsolus ~ $ ls -l /boot/EFI/com.solus-project/
total 485632
-rwxr-xr-x 1 root root   949424 May 23 15:24 bootloaderx64.efi
-rwxr-xr-x 1 root root      152 May 23 15:24 BOOTX64.CSV
-rwxr-xr-x 1 root root 65780717 May 23 15:24 freestanding-com.solus-project.nvidia-firmware
-rwxr-xr-x 1 root root    77616 May 23 15:24 grubx64.efi
-rwxr-xr-x 1 root root 80428409 Apr 25 09:58 initrd-com.solus-project.current.6.12.23-317
-rwxr-xr-x 1 root root 72239193 May  1 12:38 initrd-com.solus-project.current.6.12.23-317.nvidia
-rwxr-xr-x 1 root root 80152889 May  8 08:38 initrd-com.solus-project.current.6.14.4-318
-rwxr-xr-x 1 root root 72220777 May  8 08:38 initrd-com.solus-project.current.6.14.4-318.nvidia
-rwxr-xr-x 1 root root 83354628 May 23 15:24 initrd-com.solus-project.current.6.14.6-319
-rwxr-xr-x 1 root root 13651248 Apr 25 09:58 kernel-com.solus-project.current.6.12.23-317
-rwxr-xr-x 1 root root 13741360 May  8 08:38 kernel-com.solus-project.current.6.14.4-318
-rwxr-xr-x 1 root root 13819184 May 23 15:24 kernel-com.solus-project.current.6.14.6-319
-rwxr-xr-x 1 root root   848080 May 23 15:24 mmx64.efi

zsolus@zsolus ~ $ ls -l /usr/lib/kernel/
total 554888
-rw-r--r-- 1 root root       16 Apr 18 02:03 cmdline-6.12.23-317.current
-rw-r--r-- 1 root root       16 Apr 27 22:46 cmdline-6.14.4-318.current
-rw-r--r-- 1 root root       16 May 13 16:36 cmdline-6.14.6-319.current
drwxr-xr-x 2 root root     4096 May 23 15:23 cmdline.d
-rwxr-xr-x 1 root root 13651248 Apr 18 02:04 com.solus-project.current.6.12.23-317
-rwxr-xr-x 1 root root 13741360 Apr 27 22:46 com.solus-project.current.6.14.4-318
-rwxr-xr-x 1 root root 13819184 May 13 16:36 com.solus-project.current.6.14.6-319
-rw-r--r-- 1 root root   261840 Apr 18 02:03 config-6.12.23-317.current
-rw-r--r-- 1 root root   264575 Apr 27 22:46 config-6.14.4-318.current
-rw-r--r-- 1 root root   264716 May 13 16:36 config-6.14.6-319.current
lrwxrwxrwx 1 root root       43 May 23 15:24 current-initrd -> initrd-com.solus-project.current.6.14.6-319
lrwxrwxrwx 1 root root       36 May 23 15:24 current-vmlinux -> com.solus-project.current.6.14.6-319
lrwxrwxrwx 1 root root       36 May 23 15:24 default-current -> com.solus-project.current.6.14.6-319
-rw------- 1 root root 80428409 Apr 18 02:04 initrd-com.solus-project.current.6.12.23-317
-rw-r--r-- 1 root root 72239193 Apr 24 01:40 initrd-com.solus-project.current.6.12.23-317.nvidia
-rw------- 1 root root 80152889 Apr 27 22:46 initrd-com.solus-project.current.6.14.4-318
-rw-r--r-- 1 root root 72220777 Apr 27 22:51 initrd-com.solus-project.current.6.14.4-318.nvidia
-rw------- 1 root root 83354628 May 13 16:36 initrd-com.solus-project.current.6.14.6-319
-rw-r--r-- 1 root root 72232640 May 13 16:56 initrd-com.solus-project.current.6.14.6-319.nvidia
-rw-r--r-- 1 root root 38217687 Jul  7  2024 initrd-com.solus-project.nvidia-firmware
drwxr-xr-x 2 root root     4096 May 23 15:23 initrd.d
-rw-r--r-- 1 root root  8970066 Apr 18 02:03 System.map-6.12.23-317.current
-rw-r--r-- 1 root root  9158211 Apr 27 22:46 System.map-6.14.4-318.current
-rw-r--r-- 1 root root  9162936 May 13 16:36 System.map-6.14.6-319.current

zsolus@zsolus ~ $ ls -l /var/lib/kernel/
total 8
-rw-r--r-- 1 root root 22 May  8 07:58 k_booted_6.12.23-317.current
-rw-r--r-- 1 root root 22 May 23 15:16 k_booted_6.14.4-318.current

zsolus@zsolus ~ $ df -h /boot
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       489M  476M   13M  98% /boot

zsolus@zsolus ~ $ sudo env CBM_DEBUG=1 clr-boot-manager update
[DEBUG] cbm (../src/cli/cli.c:L142): No such file: //etc/kernel/update_efi_vars
[INFO] cbm (../src/bootman/bootman.c:L815): Current running kernel: 6.14.4-318.current
[INFO] cbm (../src/bootman/sysconfig.c:L179): Discovered UEFI ESP: /dev/disk/by-partuuid/6a70da2c-002c-4b3e-a369-38db22ec3fba
[INFO] cbm (../src/bootman/sysconfig.c:L256): Fully resolved boot device: /dev/sda1
[DEBUG] cbm (../src/bootman/bootman.c:L179): No console configuration in //etc/vconsole.conf
[DEBUG] cbm (../src/bootman/bootman.c:L145): shim-systemd caps: 0x26, wanted: 0x26
[DEBUG] cbm (../src/bootman/bootman.c:L160): UEFI boot now selected (shim-systemd)
[INFO] cbm (../src/bootman/bootman.c:L835): path ///etc/kernel/initrd.d does not exist
[DEBUG] cbm (../src/bootman/bootman.c:L856): Non regular file: ///usr/lib64/kernel/initrd.d/.., skipping.
[DEBUG] cbm (../src/bootman/bootman.c:L856): Non regular file: ///usr/lib64/kernel/initrd.d/., skipping.
[INFO] cbm (../src/bootman/bootman.c:L531): Checking for mounted boot dir
[INFO] cbm (../src/bootman/bootman.c:L538): boot_dir is already mounted: /boot
[DEBUG] cbm (../src/bootman/update.c:L164): Now beginning update_native
[DEBUG] cbm (../src/bootman/update.c:L173): update_native: 3 available kernels
[DEBUG] cbm (../src/bootman/update.c:L191): update_native: Running kernel is (current) ///usr/lib/kernel/com.solus-project.current.6.14.4-318
[SUCCESS] cbm (../src/bootman/update.c:L205): update_native: Bootloader updated
[DEBUG] cbm (../src/bootman/kernel.c:L650): installing extra initrd: /usr/lib64/kernel/initrd-com.solus-project.current.6.14.4-318.nvidia
[DEBUG] cbm (../src/bootloaders/systemd-class.c:L220): adding extra initrd to bootloader: initrd-com.solus-project.current.6.14.4-318.nvidia
[SUCCESS] cbm (../src/bootman/update.c:L220): update_native: Repaired running kernel ///usr/lib/kernel/com.solus-project.current.6.14.4-318
[DEBUG] cbm (../src/bootman/update.c:L230): update_native: Checking kernels for type current
[INFO] cbm (../src/bootman/update.c:L243): update_native: Default kernel for type current is ///usr/lib/kernel/com.solus-project.current.6.14.6-319
[DEBUG] cbm (../src/bootman/kernel.c:L650): installing extra initrd: /usr/lib64/kernel/initrd-com.solus-project.current.6.14.6-319.nvidia
[FATAL] cbm (../src/bootman/kernel.c:L740): Failed to install extra initrds /usr/lib64/kernel/initrd-com.solus-project.current.6.14.6-319: No space left on device
[FATAL] cbm (../src/bootman/update.c:L250): Failed to install default-current kernel: ///usr/lib/kernel/com.solus-project.current.6.14.6-319
```

**Comment by zmaint** [comment]
Would it be possible to add an error message for those that are updating via the software center?   I update from the terminal, but most of the friends and family that I have that are on Solus use the software center and are not techies.   That would help them know they need to ask for help to manually clear out those old kernels before they reboot and are left with an unusable system.   I could also log in remotely at that point and fix things rather than try to walk them through what to type in over the phone.  Thanks!

**Comment by silkeh** [comment]
@zmaint seems like the Nvidia firmware has become sufficiently large that three kernels and firmware no longer fits on a 512 MiB `/boot`. I think this is probably a different issue than originally supported (title mentions 1 GiB `/boot`), but it's definitively an issue nonetheless.

I think the change in #10 should fix this issue for you. [This comment](https://github.com/getsolus/clr-boot-manager/pull/10#issuecomment-2912550348) contains instructions on testing it. Note that this PR has not gone through thorough testing or review, so it is advisable to make sure you can do a [boot rescue](https://help.getsol.us/docs/user/troubleshooting/boot-rescue/) if things go wrong.

> Would it be possible to add an error message for those that are updating via the software center?

I don't think we're going to spend much time on the Software Center at this point, but I'll discuss what we can do to get this feedback in GNOME Software and Plasma Discover (which will replace the Software Center in the near future).

**Comment by zmaint** [comment]
@silkeh Thank you!  Will this change in #10 eventually get tested and rolled out to everyone?

**Comment by silkeh** [comment]
@zmaint: definitely!

**Comment by LinuxinaBit** [comment]
I have a similar issue and was directed here from the Matrix.
```
aaron@aaron-solus ~ $ sudo clr-boot-manager update
[ERROR] cbm (../src/lib/bootvar.c:L372): efi_set_variable() failed: No space left on device
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L365): Cannot create EFI variable (boot entry)
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L366): Please manually update your bios to add a boot entry for Solus
```
If you still need the info, here are the outputs to the commands you mentioned previously, hopefully it helps :)
```
aaron@aaron-solus ~ $ sudo clr-boot-manager list-kernels
ls -l /boot/loader/entries/
ls -l /boot/EFI/com.solus-project/
ls -l /usr/lib/kernel/
ls -l /var/lib/kernel/
df -h /boot
* com.solus-project.current.6.14.6-319
total 4
-rwxr-xr-x 1 root root 271 May 17 08:29 Solus-current-6.14.6-319.conf
total 96740
-rwxr-xr-x 1 root root   949424 May 29 22:41 bootloaderx64.efi
-rwxr-xr-x 1 root root      152 May 29 22:41 BOOTX64.CSV
-rwxr-xr-x 1 root root    77616 May 29 22:41 grubx64.efi
-rwxr-xr-x 1 root root 83354628 May 17 08:29 initrd-com.solus-project.current.6.14.6-319
-rwxr-xr-x 1 root root 13819184 May 17 08:29 kernel-com.solus-project.current.6.14.6-319
-rwxr-xr-x 1 root root   848080 May 29 22:41 mmx64.efi
total 104120
-rw-r--r-- 1 root root       16 May 13 16:36 cmdline-6.14.6-319.current
-rwxr-xr-x 1 root root 13819184 May 13 16:36 com.solus-project.current.6.14.6-319
-rw-r--r-- 1 root root   264716 May 13 16:36 config-6.14.6-319.current
lrwxrwxrwx 1 root root       43 May 17 08:29 current-initrd -> initrd-com.solus-project.current.6.14.6-319
lrwxrwxrwx 1 root root       36 May 17 08:29 current-vmlinux -> com.solus-project.current.6.14.6-319
lrwxrwxrwx 1 root root       36 May 17 08:29 default-current -> com.solus-project.current.6.14.6-319
-rw------- 1 root root 83354628 May 13 16:36 initrd-com.solus-project.current.6.14.6-319
-rw-r--r-- 1 root root  9162936 May 13 16:36 System.map-6.14.6-319.current
total 4
-rw-r--r-- 1 root root 22 May 29 22:39 k_booted_6.14.6-319.current
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1 1022M  128M  895M  13% /boot
```
```
aaron@aaron-solus ~ $ sudo env CBM_DEBUG=1 clr-boot-manager update
[DEBUG] cbm (../src/cli/cli.c:L142): No such file: //etc/kernel/update_efi_vars
[INFO] cbm (../src/bootman/bootman.c:L815): Current running kernel: 6.14.6-319.current
[INFO] cbm (../src/bootman/sysconfig.c:L179): Discovered UEFI ESP: /dev/disk/by-partuuid/8e338c6f-d049-46e3-9a44-5442605e3fa3
[INFO] cbm (../src/bootman/sysconfig.c:L256): Fully resolved boot device: /dev/nvme0n1p1
[DEBUG] cbm (../src/bootman/bootman.c:L184): Loading vconsole.conf from //etc/vconsole.conf
[DEBUG] cbm (../src/bootman/bootman.c:L145): shim-systemd caps: 0x26, wanted: 0x26
[DEBUG] cbm (../src/bootman/bootman.c:L160): UEFI boot now selected (shim-systemd)
[INFO] cbm (../src/bootman/bootman.c:L835): path ///etc/kernel/initrd.d does not exist
[INFO] cbm (../src/bootman/bootman.c:L835): path ///usr/lib64/kernel/initrd.d does not exist
[INFO] cbm (../src/bootman/bootman.c:L531): Checking for mounted boot dir
[INFO] cbm (../src/bootman/bootman.c:L538): boot_dir is already mounted: /boot
[DEBUG] cbm (../src/bootman/update.c:L164): Now beginning update_native
[DEBUG] cbm (../src/bootman/update.c:L173): update_native: 1 available kernels
[DEBUG] cbm (../src/bootman/update.c:L191): update_native: Running kernel is (current) ///usr/lib/kernel/com.solus-project.current.6.14.6-319
[ERROR] cbm (../src/lib/bootvar.c:L372): efi_set_variable() failed: No space left on device
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L365): Cannot create EFI variable (boot entry)
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L366): Please manually update your bios to add a boot entry for Solus
[SUCCESS] cbm (../src/bootman/update.c:L205): update_native: Bootloader updated
[SUCCESS] cbm (../src/bootman/update.c:L220): update_native: Repaired running kernel ///usr/lib/kernel/com.solus-project.current.6.14.6-319
[DEBUG] cbm (../src/bootman/update.c:L230): update_native: Checking kernels for type current
[INFO] cbm (../src/bootman/update.c:L243): update_native: Default kernel for type current is ///usr/lib/kernel/com.solus-project.current.6.14.6-319
[SUCCESS] cbm (../src/bootman/update.c:L255): update_native: Installed tip for current: ///usr/lib/kernel/com.solus-project.current.6.14.6-319
[SUCCESS] cbm (../src/bootman/update.c:L269): update_native: Installed last_good kernel (current) (///usr/lib/kernel/com.solus-project.current.6.14.6-319)
[DEBUG] cbm (../src/bootman/update.c:L280): update_native: Analyzing for type current: ///usr/lib/kernel/com.solus-project.current.6.14.6-319
[DEBUG] cbm (../src/bootman/update.c:L285): update_native: Skipping running kernel
[INFO] cbm (../src/bootman/bootman.c:L531): Checking for mounted boot dir
[INFO] cbm (../src/bootman/bootman.c:L538): boot_dir is already mounted: /boot
[SUCCESS] cbm (../src/bootman/update.c:L338): update_native: Default kernel for current is ///usr/lib/kernel/com.solus-project.current.6.14.6-319
[DEBUG] cbm (../src/bootman/update.c:L353): No kernel removals found
```
And here's a screenshot of GParted if that helps as well:
![Image](https://github.com/user-attachments/assets/c152f7a5-6e03-48e6-829a-026f6c33edad)

**Comment by LinuxinaBit** [comment]
This is still happening on a fresh install of Solus (at least after updating everything fully):

```
aaron@aaron-solus ~ $ sudo clr-boot-manager update
[ERROR] cbm (../src/lib/bootvar.c:L372): efi_set_variable() failed: No space left on device
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L365): Cannot create EFI variable (boot entry)
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L366): Please manually update your bios to add a boot entry for Solus
aaron@aaron-solus ~ $ 
```

```
aaron@aaron-solus ~ $ sudo clr-boot-manager mount-boot
aaron@aaron-solus ~ $ sudo clr-boot-manager list-kernels
ls -l /boot/loader/entries/
ls -l /boot/EFI/com.solus-project/
ls -l /usr/lib/kernel/
ls -l /var/lib/kernel/
df -h /boot
* com.solus-project.current.6.14.11-320
total 4
-rwxr-xr-x 1 root root 299 Jun 30 15:08 Solus-current-6.14.11-320.conf
total 96948
-rwxr-xr-x 1 root root   949424 Jul  2 09:45 bootloaderx64.efi
-rwxr-xr-x 1 root root      152 Jul  2 09:45 BOOTX64.CSV
-rwxr-xr-x 1 root root    77616 Jul  2 09:45 grubx64.efi
-rwxr-xr-x 1 root root 83559973 Jun 30 15:08 initrd-com.solus-project.current.6.14.11-320
-rwxr-xr-x 1 root root 13827376 Jun 30 15:08 kernel-com.solus-project.current.6.14.11-320
-rwxr-xr-x 1 root root   848080 Jul  2 09:45 mmx64.efi
total 104328
-rw-r--r-- 1 root root       16 Jun 26 18:56 cmdline-6.14.11-320.current
-rwxr-xr-x 1 root root 13827376 Jun 26 18:57 com.solus-project.current.6.14.11-320
-rw-r--r-- 1 root root   264741 Jun 26 18:56 config-6.14.11-320.current
lrwxrwxrwx 1 root root       44 Jun 30 15:08 current-initrd -> initrd-com.solus-project.current.6.14.11-320
lrwxrwxrwx 1 root root       37 Jun 30 15:08 current-vmlinux -> com.solus-project.current.6.14.11-320
lrwxrwxrwx 1 root root       37 Jun 30 15:08 default-current -> com.solus-project.current.6.14.11-320
-rw------- 1 root root 83559973 Jun 26 18:57 initrd-com.solus-project.current.6.14.11-320
-rw-r--r-- 1 root root  9167326 Jun 26 18:56 System.map-6.14.11-320.current
total 4
-rw-r--r-- 1 root root 22 Jul  2 09:43 k_booted_6.14.11-320.current
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1 1022M   96M  927M  10% /boot
aaron@aaron-solus ~ $ 
```

```
aaron@aaron-solus ~ $ sudo env CBM_DEBUG=1 clr-boot-manager update
[DEBUG] cbm (../src/cli/cli.c:L142): No such file: //etc/kernel/update_efi_vars
[INFO] cbm (../src/bootman/bootman.c:L815): Current running kernel: 6.14.11-320.current
[INFO] cbm (../src/bootman/sysconfig.c:L179): Discovered UEFI ESP: /dev/disk/by-partuuid/2a125bfd-cb70-477e-9ed5-36ea0ac8fd92
[INFO] cbm (../src/bootman/sysconfig.c:L256): Fully resolved boot device: /dev/nvme0n1p1
[DEBUG] cbm (../src/bootman/bootman.c:L184): Loading vconsole.conf from //etc/vconsole.conf
[DEBUG] cbm (../src/bootman/bootman.c:L145): shim-systemd caps: 0x26, wanted: 0x26
[DEBUG] cbm (../src/bootman/bootman.c:L160): UEFI boot now selected (shim-systemd)
[INFO] cbm (../src/bootman/bootman.c:L835): path ///etc/kernel/initrd.d does not exist
[INFO] cbm (../src/bootman/bootman.c:L835): path ///usr/lib64/kernel/initrd.d does not exist
[INFO] cbm (../src/bootman/bootman.c:L531): Checking for mounted boot dir
[INFO] cbm (../src/bootman/bootman.c:L538): boot_dir is already mounted: /boot
[DEBUG] cbm (../src/bootman/update.c:L164): Now beginning update_native
[DEBUG] cbm (../src/bootman/update.c:L173): update_native: 1 available kernels
[DEBUG] cbm (../src/bootman/update.c:L191): update_native: Running kernel is (current) ///usr/lib/kernel/com.solus-project.current.6.14.11-320
[ERROR] cbm (../src/lib/bootvar.c:L372): efi_set_variable() failed: No space left on device
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L365): Cannot create EFI variable (boot entry)
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L366): Please manually update your bios to add a boot entry for Solus
[SUCCESS] cbm (../src/bootman/update.c:L205): update_native: Bootloader updated
[SUCCESS] cbm (../src/bootman/update.c:L220): update_native: Repaired running kernel ///usr/lib/kernel/com.solus-project.current.6.14.11-320
[DEBUG] cbm (../src/bootman/update.c:L230): update_native: Checking kernels for type current
[INFO] cbm (../src/bootman/update.c:L243): update_native: Default kernel for type current is ///usr/lib/kernel/com.solus-project.current.6.14.11-320
[SUCCESS] cbm (../src/bootman/update.c:L255): update_native: Installed tip for current: ///usr/lib/kernel/com.solus-project.current.6.14.11-320
[SUCCESS] cbm (../src/bootman/update.c:L269): update_native: Installed last_good kernel (current) (///usr/lib/kernel/com.solus-project.current.6.14.11-320)
[DEBUG] cbm (../src/bootman/update.c:L280): update_native: Analyzing for type current: ///usr/lib/kernel/com.solus-project.current.6.14.11-320
[DEBUG] cbm (../src/bootman/update.c:L285): update_native: Skipping running kernel
[INFO] cbm (../src/bootman/bootman.c:L531): Checking for mounted boot dir
[INFO] cbm (../src/bootman/bootman.c:L538): boot_dir is already mounted: /boot
[SUCCESS] cbm (../src/bootman/update.c:L338): update_native: Default kernel for current is ///usr/lib/kernel/com.solus-project.current.6.14.11-320
[DEBUG] cbm (../src/bootman/update.c:L353): No kernel removals found
aaron@aaron-solus ~ $ 
```

It's very possible I screwed something up, but all I did before this was:

```
aaron@aaron-solus ~ $ sudo clr-boot-manager set-timeout 1 && sudo clr-boot-manager update
New timeout value is: 1
[ERROR] cbm (../src/lib/bootvar.c:L372): efi_set_variable() failed: No space left on device
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L365): Cannot create EFI variable (boot entry)
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L366): Please manually update your bios to add a boot entry for Solus
aaron@aaron-solus ~ $ 
```

Obligatory GParted screenshot:

![Image](https://github.com/user-attachments/assets/8913ec9b-6c5e-42b1-95d7-90e29c7ac9eb)

**Comment by silkeh** [comment]
@LinuxinaBit: that looks like a firmware issue. Your boot partition looks normal.

```
[ERROR] cbm (../src/lib/bootvar.c:L372): efi_set_variable() failed: No space left on device
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L365): Cannot create EFI variable (boot entry)
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L366): Please manually update your bios to add a boot entry for Solus
```

This indicates that the issue is when updating the EFI variables. These are internal to your BIOS/EFI firmware. You could try updating your BIOS to see if that helps, but if your system boots normally the message can be ignored (the rest of the output looks normal and you are on the latest kernel).

**Comment by zmaint** [comment]
Has the fix rolled out yet?  I just ran into the issue again with the latest update.  Had 3 kernels (+all the Nvidia drivers) and no room to install the new kernel.

**Comment by TraceyC77** [comment]
> Has the fix rolled out yet?

This issue is still open, which means a fix has not been implemented yet.
Also, the linked pull request #10 is still in Draft state, so it hasn't merged yet.

**Comment by zmaint** [comment]
Still having issues, does not seem that partition size matters.  It seems to me that it's the combination of AMD CPU and Nvidia GPU.  My PC has 500mb, it's an old install, but I'll still get an extra kernel.   The other PC is a newer install has 1gb partition and will end up with 5 kernels.   The only thing the increased size done is let me go longer between having to manually delete kernels.  Let me know if there is any additional information I can provide.
```
zsolus@zsolus \~ $ sudo clr-boot-manager mount-boot
 
zsolus@zsolus \~ $ sudo clr-boot-manager list-kernels
 com.solus-project.current.7.0.14-346
\* com.solus-project.current.7.0.13-345
 com.solus-project.current.7.0.12-344

zsolus@zsolus \~ $ sudo clr-boot-manager remove-kernel com.solus-project.current.7.0.12-344 
zsolus@zsolus \~ $ sudo clr-boot-manager set-kernel com.solus-project.current.7.0.14-346 
zsolus@zsolus \~ $ sudo clr-boot-manager update 
zsolus@zsolus \~ $ sudo usysconf run -f
```
